### ISSUE TITLE
User is able to get free VM

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#174]
Take a look at @Nuanda [comment](https://github.com/dice-cyfronet/atmosphere/pull/162/files#r30019311)

**Comment by tbartynski** [comment]
I've had a short discussion about it with @Nuanda and looked at the code. It seems that the problem occurs if for some reason in 

https://github.com/dice-cyfronet/atmosphere/blob/master/app/services/atmosphere/appliance_vms_manager.rb#L48

it fails to save appliance. Since satisfier is run in background we already have the appliance object in the DB and we only update it's state. I really do not see a good reason why updating the state should fail (other than problems with DB availability or hardware).
I see three possible solutions:
1. won't fix this since we don't handle rollback anywhere in Atmosphere and this problem is unlikely to happen
2. we invoke billing even if we failed to save appl but we loose information what happened
3. we try to handle rollbacks/retries everywhere in Atmosphere - huge task.

@nowakowski, @mkasztelnik what do you think?

**Comment by mkasztelnik** [comment]
IMHO solution nr 1, because right now billing has rather informative meaning.

**Comment by nowakowski** [comment]
I would concur with @mkasztelnik  - plus we shouldn't invoke billing on an unsatisfied appliance anyway.
